# Generated by Django 4.0.6 on 2022-08-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variacao',
        ),
    ]
