# Generated by Django 4.0.6 on 2022-08-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_delete_variacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_marketing_promocional',
        ),
    ]
