# Generated by Django 4.0.6 on 2022-08-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_produto_preco_marketing_promocional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
